spring:
  application:
    name: jt-car
#读写分离的多数据源
#读库  datasource:
    read:      jdbc-url: jdbc:mysql:///mark_read?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
     
      
 #写库  
    write:
      jdbc-url: jdbc:mysql:///market?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver  redis:    host: 192.168.42.132
    port: 6379     
server:  servlet:    context-path: /car  port: 8004
#eureka相关配置
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

#暴露监控断点，供hystrix仪表盘监控健康状态  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
turbine:
  instanceUrlSuffix: /hystrix.stream
