spring:
  application:
    name: jt-eureka  redis:    host: 192.168.42.132
    port: 6379
server:  port: 8000  servlet:    context-path: /
eureka:
  server:
  #关闭eureka的自我保护机制（开发阶段）    enable-self-preservation: false
  instance:
    #prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
    hostname: eureka1 #以服务名注册到服务中心（集群之间互相区分）
    #最后一次心跳后间隔多久没有心跳认定服务不可用（一次心跳30秒）
    lease-expiration-duration-in-seconds: 60
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka    register-with-eureka: false
    fetch-registry: false

    