server:
  port: 8007
spring:
  application:
    name: turbing
  redis:
    host: 192.168.40.152
    port: 6379 
    
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
# turbine配置
turbine:
  # 需要监控的应用名称，默认逗号隔开，内部使用Stringutils.commaDelimitedListToStringArray分割
  app-config: jt-car,jt-user
  # false 时 在本机才是时 监控中host集群数会为1了 因为本地host是一样的
  #combine-host-port: true
  # 集群名称
  cluster-name-expression: new String('default')



