server:
  port: 8005
  servlet:    context-path: /web
spring:  application:    name: jt-web
  redis:    host: 192.168.40.152
    port: 6379#  mvc:#    view:#      prefix: .html
#      suffix: classpath:/view
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka

