#端口号
server:
  port: 8001
#数据源
spring:  application:    name: jt-zuul  datasource:    driver-class-name: com.jdbc.mysql.Driver
    url: jdbc:mysql:///jtsys?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 192.168.40.152
    port: 6379
#注册到eureka中
eureka:  instance:
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
zuul:
    #哪些服务
  routes:
    jt-order:
      path: /order/**
      serviceId: jt-order
      #去除前缀
      stripPrefix: false
    jt-user:
      path: /user/**
      serviceId: jt-user
      stripPrefix: false
    jt-web:
      path: /web/**
      serviceId: jt-web
      stripPrefix: false
    jt-car:
      path: /car/**
      serviceId: jt-car
      stripPrefix: false
#ribbon:#  eureka:#    enabled: false
  
  #开启重试

  retryable: true
#超时时间和重试次数的配置
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1